config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, :path => 'accounts', controllers: { registrations: "registrations"}
  get 'home/index'
  resources :articles, only: [:show]

  namespace :administrator do
    resources :articles
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
      if user.superadmin_role?
        can :manage, :all
        can :access, :rails_admin
        can :manage, :dashboard      
      else
        can :read, :all
      end

   if user.editor_role?
      can :access, :rails_admin
      can :manage, Article
   end

   if user.user_role?
    can :read, :all
   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    belongs_to :author, class_name: 'User'
    belongs_to :category, class_name: 'Category'
end

app/models/category.rb
class Category < ApplicationRecord
   has_many :articles, foreign_key:  'category_id'
end

app/models/page.rb
class Page < ApplicationRecord
    belongs_to :author, class_name: 'User'
end

app/models/user.rb
class User < ApplicationRecord

  has_many :articles, foreign_key: 'author_id'
  has_many :pages, foreign_key: 'author_id'

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  def get_email
    self.email
  end

  def get_name
    self.name
  end
  
  def get_articles
    self.articles
  end
  

end

app/controllers/administrator/articles_controller.rb
class Administrator::ArticlesController < ApplicationController
    before_action :set_administrator_articles, only: [:show, :edit, :update, :destroy]

    def new
        @article = Article.new
    end
    
    
    
    def index
        if user_signed_in?
            @articles_user = User.find(current_user.id).get_articles
        else 
            redirect_to new_user_session_path
        end
    end

    def create
        @article = current_user.articles.build(articles_params)
        if @article.save
            redirect_to administrator_articles_path
        else
            render :new
        end
        
    end

    def create


    end


    private

    def set_administrator_articles
        @article = Article.find(params[:id])
    end


    def articles_params
        params.require(:article).permit(:title, :content, :category_id)
    end

 

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :menu
    
    private
    
    def menu
        @pages = Page.all.order("created_at DESC")
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    def show
        @articles = Article.find(params[:id])
    end
  end
  

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if user_signed_in?
      @user = User.find(current_user.id)
    end
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

    private

    def sign_up_params
        params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

    def account_update_params
        params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
    end

end

app/helpers/administrator/posts_helper.rb
module Administrator::PostsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/administrator/articles/index.html.erb
<% if current_user.superadmin_role? %>
    <% @articles_user.each do |article| %>
          <li><%= article.title %></li>
    <% end %>
<% else %>
    <p>You are not user Admin</p>
<% end %>

app/views/administrator/articles/new.html.erb
<div class="container">

    <%= simple_form_for @article, url: administrator_articles_path, :method => :post do |f| %>
  <%= f.input_field :title %>
  <%= f.input :content %>
  <%= f.button :submit %>
 
<% end %>

</div>

app/views/articles/show.html.erb
<p> <%= @articles.title %> </p>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

<% if user_signed_in? %>
     <p> <%= link_to "Dashboard Articles", administrator_articles_path%> </p>

     
     <% @user.get_articles.each do |article| %>
          <li><%= link_to  article.title , article_path(article.id) %></li>
     <% end %>
     

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cmspro</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">CMSpro</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <% @pages.each do |page| %>
    <li class="nav-item">
        <%= link_to page.title, root_path,class: 'nav-link' %> 
    </li>
  <% end %>

    
      <% if user_signed_in? %>
     <li class="nav-item">
        <%= link_to "Articles Dashboard", administrator_articles_path,class: 'nav-link' %> 
    </li>
    <li class="nav-item">
        <%= link_to "Sign out", destroy_user_session_path, :method => :delete, class: 'nav-link'%> 
    </li>
  <% else %>
    <li class="nav-item text-right">
        <%= link_to "Login", new_user_session_path,class: 'nav-link' %> 
    </li>
  <% end %>
  
</nav>
  
  </header>
    <%= yield %>
  </body>
</html>